export const data = {
    notes: [
        { id: "24", nomi: "1 L Pepsi", soni: "10" },
        { id: "25", nomi: "1 L Coca-cola", soni: "11" },
        { id: "26", nomi: "Perla 4 Perla 0", soni: "1" },
        { id: "27", nomi: "Staples Deli 0", soni: "25" },
        { id: "28", nomi: "Paynet Paynet 0", soni: "1" },
        { id: "29", nomi: "Dlya zavtrok Sherin 900g", soni: "1" },
        { id: "30", nomi: "EVN-A250-4 (250 WT) EPA Nasos vodniy", soni: "20" },
        { id: "31", nomi: "premium 80L Royal", soni: "10" },
        { id: "32", nomi: "A 225 5G Samsung 0", soni: "1" },
        { id: "33", nomi: "1/L Family", soni: "1" },
        { id: "34", nomi: "A 325 5G Samsung 0", soni: "2" },
        { id: "61", nomi: "mishka", soni: "10" },
        { id: "62", nomi: "Pepsi", soni: "1" },
        { id: "64", nomi: "Pepsi", soni: null },
        { id: "65", nomi: "Pepsi", soni: null },
        { id: "66", nomi: "Pepsi", soni: null },
        { id: "67", nomi: "Test7", soni: null },
        { id: "73", nomi: "Array", soni: null },
        { id: "74", nomi: "Array", soni: null },
        { id: "75", nomi: "Array", soni: "21" },
        { id: "76", nomi: "Array", soni: null },
        { id: "77", nomi: "Array", soni: null },
        { id: "78", nomi: "Array", soni: null },
        { id: "83", nomi: "Abu_best", soni: null },
        { id: "84", nomi: "Abu_best", soni: null },
        { id: "85", nomi: "Abu_best", soni: null },
        { id: "86", nomi: "Abu_best", soni: null },
        { id: "87", nomi: "Abu_best", soni: null },
        { id: "88", nomi: "Abu_best", soni: null },
        { id: "89", nomi: "Abu_best", soni: null },
        { id: "90", nomi: "sdgetf", soni: null },
        { id: "93", nomi: "Alhamdulillah", soni: null },
        { id: "95", nomi: "Alhamdulillah", soni: null },
        { id: "96", nomi: "bismillah", soni: null },
        { id: "97", nomi: "bismillah", soni: null },
        { id: "98", nomi: "bismillah", soni: null },
        { id: "99", nomi: "bismillah", soni: null },
        { id: "100", nomi: "bismillah", soni: null },
        { id: "101", nomi: "Salom", soni: null },
        { id: "102", nomi: "Yangi", soni: null },
        { id: "103", nomi: "Ali", soni: null },
        { id: "104", nomi: "Coca cola", soni: null },
        { id: "105", nomi: "Noutbuk", soni: null },
        { id: "106", nomi: "Birinchi", soni: null },
        { id: "107", nomi: "besh", soni: null },
        { id: "108", nomi: "shunaqa", soni: null },
        { id: "109", nomi: "dfd", soni: null },
        { id: "113", nomi: "fd", soni: null },
        { id: "114", nomi: "sdc", soni: null },
        { id: "115", nomi: "1bir", soni: null },
        { id: "116", nomi: " ikki", soni: null },
        { id: "117", nomi: "test", soni: "5" },
        { id: "118", nomi: "6", soni: "" },
        { id: "119", nomi: "7", soni: "" },
        { id: "120", nomi: "asdasa", soni: "5" },
        { id: "122", nomi: "frefef", soni: "1" },
        { id: "123", nomi: "ggrgr", soni: "56" },
        { id: "124", nomi: "wd", soni: "4" },
        { id: "125", nomi: "ed", soni: "9" },
        { id: "126", nomi: "sdw", soni: "3" },
        { id: "127", nomi: "dwsd", soni: "65" },
        { id: "129", nomi: "hu", soni: "6" },
        { id: "130", nomi: "ww", soni: "4" },
        { id: "132", nomi: "t5t5", soni: "5" },
        { id: "133", nomi: "fhfh", soni: "10" },
        { id: "134", nomi: "noutbuk", soni: "5" },
        { id: "135", nomi: "shshsh", soni: "1" },
        { id: "136", nomi: "etudxkj", soni: "365" },
    ],
};
